vacp2p/nim-quic

quic.nimble, quic/bits.nim, quic/packets.nim, quic/packets/connectionid.nim, quic/packets/datagram.nim, quic/packets/length.nim, quic/packets/packet.nim, quic/packets/read.nim, quic/packets/write.nim, tests/quic/testBits.nim, tests/quic/testPackets.nim
Converts Packet struct to use object variants.
Adds version negotiation fields and length.
=> Rewrite packet parsing

quic.nim, quic/packets.nim, quic/packets/packet.nim, quic/packets/read.nim, quic/packets/write.nim, quic/version.nim, tests/quic/testPacketLength.nim, tests/quic/testPacketReading.nim, tests/quic/testPacketWriting.nim, tests/quic/testPackets.nim
Includes changes to testPacketReading that make this fix easier.
=> Fix: packet length includes both packet number and payload

quic/transport/ngtcp2/stream/drainingstate.nim, quic/transport/ngtcp2/stream/openstate.nim, quic/transport/ngtcp2/streams.nim, tests/quic/testStreams.nim
When we receive a message that a stream is closed by the peer, the stream state machine did not switch from `open` to `closed`. This led to the occasional failure that was observed in #21. This pull request ensures that it does switch to the `closed` state.
When the message queue for the stream is not yet empty, then the stream state will go from `open` to `draining`, allowing the messages in the queue to be read before switching to the `closed` state.
Fixes #21
=> Drain streams that were closed by peer

quic/transport/ngtcp2/stream/openstate.nim, quic/transport/ngtcp2/streams.nim, tests/quic/testStreams.nim
The `AsyncQueue` in `OpenStream` was not bound in size. This can lead to memory problems when the receiving peer cannot read fast enough to keep up with the sending peer. This PR fixes that by using the maximum stream offset from QUIC correctly.
Writing to streams is blocked when the maximum stream offset is reached. Previously we extended this offset when data was *added* to the read queue of the receiving peer. Now we only extend it once data has been *removed* from the queue, thereby limiting the queue size.
=> Limit size of stream queue

.github/workflows/test.yml, quic.nimble, quic/helpers/errorasdefect.nim, quic/helpers/noerrors.nim, quic/transport/ngtcp2/connection.nim, quic/transport/ngtcp2/errors.nim, quic/transport/ngtcp2/stream/openstate.nim, quic/transport/packets.nim, quic/transport/packets/length.nim, quic/transport/packets/packet.nim, quic/transport/packets/read.nim, quic/transport/quicclientserver.nim, quic/transport/timeout.nim
Latest version of Chronos disallows errors to escape from timeout callbacks. Any Errors that are raised in the connection timeout callback should not happen and are therefore are converted to Defects.
Uses `upraises` for exception tracking across Nim 1.2 and 1.4.
Fixes Ngtcp2 error hierarchy to match that of Nim; we now have an Ngtcp2Error and Ngtcp2Defect.
=> Handle errors in timeouts

quic/connection.nim, tests/helpers/udp.nim, tests/quic/testConnection.nim, tests/testAll.nim
When the underlying UDP transport fails, make sure that it is handled gracefully.
Before this change, any TransportError would become a FutureDefect (and crash the application).
=> Drop connection when underlying UDP transport fails

quic/connection.nim
Using this in nim-libp2p creates the error:
`/Users/runner/work/nim-libp2p/nim-libp2p/nimbledeps/pkgs/json_serialization-#85b7ea093cb85ee4f433a617b97571bd709d30df/json_serialization/writer.nim(249, 12) Error: fatal error: Failed to convert to JSON an unsupported type: Port`
Also
```nim
import json_serialization/writer
import chronos
toJSON(initTAddress("127.0.0.1:1234"))
```
fails with
/nim-libp2p/nimbledeps/pkgs/json_serialization-#8a4ed98bbd0a9479df15af2fa31da38a586ea6d5/json_serialization/writer.nim(203, 8) template/generic instantiation of enumInstanceSerializedFields from here
/nim-libp2p/nimbledeps/pkgs/serialization-#298a9554a885b2df59737bb3461aac8d0d339724/serialization/object_serialization.nim(48, 40) Error: type mismatch: got <uint16>
but expected one of:
iterator fieldPairs[S: …
=> chore: remove remote addr from log

quic/connection.nim
It was raising a defect on nim-libp2p tests sometimes as a future can't fail if it is already finished.
=> fix: doesn't fail loop fut if it is already finished

quic/transport/ngtcp2/native/streams.nim, quic/transport/ngtcp2/stream/closedstate.nim, quic/transport/ngtcp2/stream/openstate.nim
I noticed that since we currently do not handle half open states, it was possible for a dangling pointer to be left when closing an stream, since before the code did not actively call setUserData with a nil state. In this PR i assume that calling stream.close() is similar to Go in which it closes both the Read and the Write. hence as soon as Close state is entered, it will clear the stream userdata from ngtcp2.
This might need some changes if we decide in the future to handle half closed states (not sure tho)
=> fix: close should clean stream userdata

quic/transport/framesorter.nim, tests/quic/testFramesorter.nim
- ranges seem unnecessary in `fs` as they were only used for `isComplete` function. however `isComplete` can be calculated simpler:
`number of emitted bytes + number of bytes in buffer == total bytes`.
in the context of pr number of emitted bytes is `fs.emitPos`; number of bytes in buffer is `len(fs.buffer)` and total bytes is `fs.totalBytes`.
- removed usage of units - to remove unnecessary conversions, same properties are preserved by keeping uints in interface.
=> refactor(framesorter): remove ranges usage

quic/transport/framesorter.nim, tests/quic/testFramesorter.nim
- added fast path when insert happens at exactly the same position to currently emitting position. in this case we can emit entire input chunk of data as whole. in addition to this we need to check if there is buffered data to be emitted.
- tests have changed a bit to be more robust - when checking queue content it's better to check entire content without checking individual pieces.
this can improve performance and reduce memory trashing.
=> feat(framesorter): add fastpath for emitting data

quic/transport/ngtcp2/native/streams.nim, quic/transport/ngtcp2/stream/closedstate.nim, quic/transport/ngtcp2/stream/openstate.nim, quic/transport/stream.nim, tests/quic/testStreams.nim
Fixes the error seen here: https://github.com/vacp2p/nim-libp2p/actions/runs/15193656027/job/42732413624?pr=1392 that happens frequently with zig, due to them sending a reset when shutting down a stream
```
dialer-1    | Traceback (most recent call last)
dialer-1    | /app/nim-libp2p/tests/transport-interop/main.nim(110) main
dialer-1    | /app/nim-libp2p/nimbledeps/pkgs/chronos-#b55e2816eb45f698ddaca8d8473e401502562db2/chronos/internal/asyncfutures.nim(638) waitFor
dialer-1    | /app/nim-libp2p/nimbledeps/pkgs/chronos-#b55e2816eb45f698ddaca8d8473e401502562db2/chronos/internal/asyncfutures.nim(624) pollFor
dialer-1    | /app/nim-libp2p/nimbledeps/pkgs/chronos-#b55e2816eb45f698ddaca8d8473e401502562db2/chronos/internal/asyncengine.nim(150) poll
dialer-1    | …
```
=> fix: closing stream on stream reset

quic/transport/ngtcp2/connection/closedstate.nim, quic/transport/ngtcp2/connection/closingstate.nim, quic/transport/ngtcp2/connection/disconnectingstate.nim, quic/transport/ngtcp2/connection/drainingstate.nim, quic/transport/ngtcp2/connection/openstate.nim, quic/transport/quicconnection.nim
This will ensure you can access the certificates used for a connection, regardless of the connection state
=> refactor: make certificates part of the connection

quic/api.nim, quic/transport/ngtcp2/stream/closedstate.nim, quic/transport/ngtcp2/stream/openstate.nim, quic/transport/stream.nim, tests/quic/testStreams.nim
Add closeWrite() method to support half-close semantics for QUIC streams, enabling protocols like perf to close write side while keeping read side open for bidirectional communication.
Changes:
- Add closeWrite() method to StreamState base class and implementations
- Track writeFinSent flag in OpenStream to prevent writes after half-close
- Export closeWrite in public API (quic/api.nim)
- Add comprehensive tests for half-close behavior
This addresses nim-libp2p issue #1530 for improved EOF detection in QUIC transport by providing proper half-close semantics that align with QUIC RFC 9000 stream state machine.
=> feat: implement half-close functionality for QUIC streams

quic/transport/framesorter.nim, quic/transport/ngtcp2/stream/openstate.nim, tests/quic/testPerf.nim, tests/testAll.nim
`read()` in open state could block when `let data = await state.incoming.get()` getting incoming data but no data is received because eof is transmitted bit later thus missing initial condition checks in `read()` .
=> fix: race condition when reading and receiving eof

quic/transport/ngtcp2/streamstate/basestate.nim, quic/transport/ngtcp2/streamstate/openstate.nim, quic/transport/ngtcp2/streamstate/receivestate.nim, quic/transport/ngtcp2/streamstate/sendstate.nim
- add `switch` and `write` procs to `BaseStreamState` which removed boilerplate code
- also bug fix: openstate should not transition to closedstate when framesorte is complete
=> chore(streamstate): add `switch` and `write` to `BaseStreamState`

quic/connection.nim, quic/transport/ngtcp2/connection/closedstate.nim, quic/transport/ngtcp2/connection/disconnectingstate.nim, quic/transport/ngtcp2/connection/drainingstate.nim, quic/transport/ngtcp2/connection/openstate.nim, quic/transport/ngtcp2/native/connection.nim, quic/transport/quicconnection.nim, quic/udp/datagram.nim
- making `Datagram` as ref object improves performance slightly
- `sink` does not have any effect on performance, but it makes sense to be used so that developers can understand where ownership of `Datagram` is
=> chore: make datagram ref object

quic/connection.nim, quic/listener.nim, quic/transport/ngtcp2/native.nim, quic/transport/ngtcp2/native/parsedatagram.nim, quic/transport/ngtcp2/native/server.nim, quic/transport/parsedatagram.nim, tests/quic/testParseDatagram.nim
- add `parseDatagramDestination`  specialized proc that only parses destination component in order to reduce total memory usage.
- rename `parseDatagram` to `parseDatagramInfo` to be more descriptive
effort for: https://github.com/vacp2p/nim-libp2p/issues/1621
=> chore: add parseDatagramDestination

quic/transport/ngtcp2/native.nim, quic/transport/ngtcp2/native/connection.nim, tests/quic/testStreams.nim
- remove shared buffer to avoid potential data races
- also eliminates one copy
=> chore: connection buffering improvement

quic/transport/ngtcp2/connection/closedstate.nim, quic/transport/ngtcp2/connection/disconnectingstate.nim
`receive` should not raise error in `ClosedConnection`. it should do nothing, or just log the event.
- `ClosedConnection` is transitioned from `DisconnectingConnection` which currently doesn't do anything on `receive`. so it doesn't make sense to start throwing in next state.
- if `ClosedConnection` do `receive` it's likely race condition in process of ending connection so we should not care 
this pr also removed some spamming logs.
=> chore: receive should not raise error

quic/transport/ngtcp2/connstate/openstate.nim, tests/quic/testQuicConnection.nim
after timeout connection is closed which will terminate all open streams and all futures waiting for streams to open.
fix: https://github.com/vacp2p/nim-quic/issues/131
=> fix: close conn after timeout
